<?php
// The parent class
require_once 'komideals/om/BaseEmailTemplatePeer.php';

// The object class
include_once 'komideals/EmailTemplate.php';

/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [Tue Apr 11 13:41:28 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package komideals 
 */
class EmailTemplatePeer extends BaseEmailTemplatePeer {

	static public function getAll() {
		$crit = new Criteria();
		$crit->addAscendingOrderByColumn(self::NAME );
		
		return self::doSelect($crit);
	}
}
