<?php
require_once 'komideals/om/BaseEmailTemplate.php';

/** 
 * The skeleton for this class was autogenerated by Propel  on:
 *
 * [Tue Apr 11 13:41:28 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package komideals 
 */
class EmailTemplate extends BaseEmailTemplate {
	
	public function save(PropelPDO $conn = null) {
		
		if($this->isNew()) {
//			$this->setIsActive(1);
//			$this->setDateCreated(time());
			
		}
		if($this->isModified()) {
			// do stuff if object has been modified
			// such as change date modified or save changes to changelog database
//			$this->setDateModified(time());
		}
		
		parent::save($conn);
	}

}
