<?php
// The parent class
require_once 'komideals/om/BaseSessionPeer.php';

// The object class
include_once 'komideals/Session.php';

/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [Tue Jan 31 10:11:39 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package komideals 
 */
class SessionPeer extends BaseSessionPeer {

}
