
<table width="100%" border="0" cellspacing="0" cellpadding="7">
	<tr> 
		<td colspan="3" nowrap class="mainText" style="padding:0pt;"><?=tabs_select_main(PAGE_C);?></td>
	</tr>
		
	<tr>
		<td style="padding:0pt;">
		<a href="http://www.visistat.com/index.php?p=RET-100" target="_blank"><img height="100" width="704" alt="VisiStat - Where Clicks Count." src="/images/img/visistat-banner.png" border=0></a>
		</td>
	</tr>
	<tr>
		<td class="mainText" valign="top">
		<p><b>Affiliate API Documentation</b></p>
		
<p>Currently, we have 2 data feeds that any affiliate may use.

<p>One feed receives a date range and affiliate ID.  It sends back any user who signed up through 
them.  It sends back the userID that we create, the userID that the affiliate initially sent us 
(so they can reference the user to a user in their systems), the date the user signed up, and 
account activation status.

<p>This example shows all users who registered through affiliate ID 273 between July and 
August 2006: /feed-list_range.htm?id=273&s=2006-07-01&e=2006-08-01

<p>The second feed allows the affiliate to grab more information about the user.  This feed receives 
an affiliate ID and a userID.  It sends back our userID, the userID that the affiliate initially sent us, the date 
created, the account activation status, the behavior id (generated by Wilshire), the 
raw javascript required for it to work, and finally the raw javascript required for 
it to work on a &quot;secure&quot; site.

<p>This example shows user information for userID 2112 who signed up through affiliate ID 273: 
/feed-pixel_code.htm?id=273uid=2112


</p>

		</td>
	</tr>
</table>

