<?php

/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [Wed Feb 15 18:00:59 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package    propel.generator.sigfly 
 */
class ImagePeer extends BaseImagePeer {

}
