<?php

/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [Thu Feb 23 17:30:51 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package    propel.generator.sigfly 
 */
class UserNotePeer extends BaseUserNotePeer {

}
