
YUI.add("bolt-form",function(Y){var $=Y.get,$j=Y.JSON;BLT.Form=function(args){this.init(args);}
BLT.Form.prototype={args:{},init:function(args){$('body').on('focus',this.focus,this);$('body').on('keyup',this.keyup,this);this.args=args;this.fields=new Array();this.animDuration=.25;},focus:function(e){var tar=e.target;this.resetFields();if(labelFor=BLT.Obj.getParent(tar,'clearField')){this.manageFieldState(labelFor);}},keyup:function(e){var tar=e.target;this.resetFields();if(labelFor=BLT.Obj.getParent(tar,'clearField')){this.manageFieldState(labelFor);}},manageFieldState:function(tar){var id=tar.get('id');if(!id){id=tar.set('id',Y.guid()).get('id');}
var labelSpan=Y.one('#'+id+' span');if(!labelSpan.hasClass('faded')){var fieldAnim=new Y.Anim({node:labelSpan,duration:this.animDuration,to:{opacity:.5}});fieldAnim.on('end',function(){fieldAnim.get('node').addClass('faded');});fieldAnim.run();var labelWidth=parseInt(labelSpan.getStyle('width'),10);if(!Y.one('#'+id+' input')){return;}
var fieldWidth=parseInt(Y.one('#'+id+' input').getStyle('width'),10);var leftMove=fieldWidth-labelWidth-7;if(leftMove>0){var posAnim=new Y.Anim({node:labelSpan,duration:this.animDuration,to:{left:leftMove}});posAnim.run();}}
var fieldVal=Y.one('#'+id+' input').get('value');if(fieldVal!=''){}else{labelSpan.removeClass('hidden');}},resetFields:function(){Y.all('.clearField').each(function(tar){var id=tar.get('id');if(!id){id=tar.set('id',Y.guid()).get('id');}
var labelSpan=Y.one('#'+id+' span');if(labelSpan.hasClass('faded')&&!labelSpan.hasClass('hidden')){var fieldAnim=new Y.Anim({node:labelSpan,duration:this.animDuration,to:{opacity:1}});fieldAnim.on('end',function(){fieldAnim.get('node').removeClass('faded');});fieldAnim.run();}
if(!Y.one('#'+id+' input')){return;}
var fieldVal=Y.one('#'+id+' input').get('value');if(fieldVal==''){var posAnim=new Y.Anim({node:labelSpan,duration:this.animDuration,to:{left:0}});posAnim.run();}else{var labelWidth=parseInt(labelSpan.getStyle('width'),10);var fieldWidth=parseInt(Y.one('#'+id+' input').getStyle('width'),10);var leftMove=fieldWidth-labelWidth-7;if(leftMove>0){var posAnim=new Y.Anim({node:labelSpan,duration:this.animDuration,to:{left:leftMove}});posAnim.run();}}},this);},displayError:function(element,error){var overlay=Y.one('.error_overlay');if(overlay&&element){var coordinates=element.getXY();var elementWidth=parseInt(element.getComputedStyle('width'),10);overlay.removeClass('hidden');Y.one('.error_overlay .container').set('innerHTML',error);var overlayWidth=parseInt(overlay.getComputedStyle('width'),10);var overlayHeight=parseInt(overlay.getComputedStyle('height'),10);overlay.setXY([coordinates[0]-(overlayWidth/2)+(elementWidth/2.2),coordinates[1]-(overlayHeight+36)]);}},hideError:function(){Y.one('.error_overlay').addClass('hidden');}}
Y.augment(BLT.Form,Y.EventTarget);});