
var f=function(Y){var $=Y.get,$j=Y.JSON;if(/opera/.test(navigator.userAgent.toLowerCase())){$(document.body).addClass('opera');}
if(/firefox/.test(navigator.userAgent.toLowerCase())){$(document.body).addClass('firefox');}
if(/chrome/.test(navigator.userAgent.toLowerCase())){$(document.body).addClass('chrome');}
if(/safari/.test(navigator.userAgent.toLowerCase())){$(document.body).addClass('safari');}
if(/msie/.test(navigator.userAgent.toLowerCase())){$(document.body).addClass('ie');}
var img=new Y.ImgLoadGroup({timeLimit:2,foldDistance:30});img.set('className','defer');Y.on('domready',function(){BLT.Obj=new BLT.Base();BLT.execute('l');},window);BLT.Base=function(){this.init();}
BLT.Base.prototype={store:{},noFbRefresh:false,init:function(){$('#doc').on('click',this.click,this);$('#doc').on('mouseover',this.mouse,this);$('#doc').on('mouseout',this.mouse,this);$('#doc').on('keyup',this.keyup,this);$('#doc').all('form.open-panel').each(function(el){var action=el.getAttribute('action');el.setAttribute('x-action',self.getUrl(action,{'.context':'xhr'}));el.setAttribute('action','#');el.setAttribute('method','get');el.on('submit',function(e){e.halt();var tar=e.target;if(tar.hasClass('loading')){return;}
tar.addClass('loading');var url=tar.getAttribute('x-action');BLT.Obj.panel.load(url,{'form':tar,'openAfter':true});tar.removeClass('loading');},this);});var self=this;this.panel=new BLT.Panel({});Y.all('.fb-login').each(function(el){el.addClass('hide');});this.fbInit();this.publish('blt-base:docclick');this.publish('blt-base:mouse');this.publish('blt-base:tblcheckboxclick');this.publish('blt-base:resize');this.publish('blt-base:fb-init');this.publish('blt-base:fb-not-con');this.publish('blt-base:fb-con');},fbInit:function(){Y.Get.script(document.location.protocol+'//connect.facebook.net/en_US/all.js',{'insertBefore':'ft','scope':BLT.Obj,'onSuccess':function(){BLT.Env.fb=true;var self=this;FB.init({appId:BLT.Env.fbApiKey,status:false,cookie:true,xfbml:true});Y.all('.fb-login').each(function(el){el.removeClass('hide');});}});},handleFbLogin:function(response){if(response.session){BLT.Env.fb=true;var self=this;BLT.Obj.fire("blt-base:fbconnected");}else{alert("You must provide us your Email Address in order to login to dailyD.");}},loadCss:function(url){Y.Get.css(url);},loadJs:function(url,args){Y.Get.script(url,args);},click:function(e){this.fire('blt-base:docclick',e);var tar=e.target,oTar=e.target,self=this;if(tar.hasClass('open-panel')&&tar.get('tagName')=='A'){e.halt();this.panel.load(tar.get('href'),{'openAfter':true});}
else if((tar=BLT.Obj.getParent(oTar,'fb-login'))){e.halt();FB.login(function(response){if(response.session){window.location.href=self.getUrl(tar.getAttribute('href'),{'.return':BLT.Env.Urls.self});}else if(response.session==null){window.location.href=self.getUrl(tar.getAttribute('href'),{'fberror':'true','.return':BLT.Env.Urls.self});}else if(response.status==='connected'){FB.getLoginStatus(function(response){if(response.session){BLT.Obj.fire("blt-base:fbconnected");if(self.noFbRefresh!==true){window.location.href=self.getUrl(tar.getAttribute('href'),{'.return':BLT.Env.Urls.self});}}},true);}},{perms:'email,publish_stream,offline_access'});}
if(!tar){return;}},keyup:function(e){var tar=oTar=e.target;if(tar.hasClass('edit-slug')){var slug=tar.get('value').replace(/ /g,'-').replace(/'/g,'');Y.one("#slug-container").set('innerHTML',slug);this.validateSlug(slug);}
if(!tar){return;}},mouse:function(e,type){var tar=oTar=e.target;this.fire('BLT-base:mouse',e);},getUrl:function(url,params){var qp=[];for(var p in params){qp.push(p+"="+encodeURIComponent(params[p]));}
return url+(url.indexOf('?')==-1?'?':'&')+qp.join('&');},getAjaxUrl:function(act,params){if(typeof params=='undefined'){params={};}
params['.token']=BLT.Env.me['xhr-token'];return this.getUrl(BLT.Env.Urls.base+'ajax/'+act,params);},getXhrUrl:function(act,params){if(typeof params=='undefined'){params={};}
params['.token']=BLT.Env.me['xhr-token'];return this.getUrl(BLT.Env.Urls.base+'xhr/'+act,params);},getParent:function(tar,g,max){if(!tar){return false;}
if(!max){max=10;}
var gt=g;var i=0;var m=max;if(typeof g=='object'){if(tar.get('tagName')==gt.tag.toUpperCase()){return tar;}
return tar.ancestor(function(el){if(i++>max){return false;}
return(el.get('tagName')==gt.tag.toUpperCase());});}
else{if(tar.hasClass(gt)){return tar;}
return tar.ancestor(function(el){if(i++>max){return false;}
return el.hasClass(gt);});}},validateSlug:function(slug){var url=BLT.Obj.getUrl(BLT.Env.Urls.base+'trucks/validate-slug',{'.context':'xhr'});var params={'method':'GET','context':this,'data':'slug='+slug,'timeout':10000,'on':{'failure':function(){},'complete':function(id,o,a){var json=false;json=$j.parse(o.responseText);var slugContainer=Y.one("span#slug-result");if(json.validslug=='good'){slugContainer.removeClass('bad');slugContainer.addClass('good');slugContainer.set('innerHTML','Available');}else{slugContainer.removeClass('good');slugContainer.addClass('bad');slugContainer.set('innerHTML','Taken');}
if(!json||json.stat!=1){return false;}}}}
Y.io(url,params);},displayMap:function(div,address){this.store.map=new google.maps.Map2(document.getElementById(div));var geocoder=new GClientGeocoder();geocoder.getLatLng(address,function(pt){BLT.Obj.store.map.setCenter(pt,13);var marker=new GMarker(pt);BLT.Obj.store.map.addOverlay(marker);});}}
Y.augment(BLT.Base,Y.EventTarget);};BLT.Env.yuiprereq.push(f);var y=YUI(BLT.Env.yuiconfig);y.use.apply(y,BLT.Env.yuiprereq);