
YUI.add("bolt-project-checkout",function(Y){var $=Y.get,$j=Y.JSON;BLT.Class.Checkout=function(cards,card){this.init(cards,card);}
BLT.Class.Checkout.prototype={store:{},init:function(cards,card){this.store.cards=cards;this.store.card=card;$('#bd').on('click',this.click,this);var handle=Y.on('key',function(e){e.halt();},'.checkout input','down:13',Y);$('.checkout').on('keyup',this.keyup,this);$('.checkout').on('blur',this.blur,this);$('#quantity').on('blur',this.validateQuantity,this);this.form=new BLT.Form();this.city='';this.form.resetFields();if($('input.buy-now')){$('input.buy-now').set('disabled',false);}
this.publish('checkout:init');this.fire('checkout',this);if($('#cards-file')){$('#cards-file').on('click',function(e){var li=BLT.Obj.getParent(e.target,{'tag':'li'});if(!li){return;}
if(li.hasClass('new-card')){$('.billing-wrap').removeClass('nodisplay');this.store.card=0;}
else{$('.billing-wrap').addClass('nodisplay');this.store.card=li.one('input').get('value');}
this.toggleShipping();},this);}
if($('input.zip')&&$('input.zip').get('value')!==""){this.geocodeZip($('input.zip').get('value'));}},click:function(e){var tar=e.target;if(tar.hasClass('purchase')){this.formError=false;this.errorNodes=new Array();tar.set('value','Processing...');return;}else if(tar.hasClass('inline-login')){try{_g.action('inline-login',{});}catch(e){}
e.halt();var email=$('input[name=email]').get('value');var pass=$('input[name=password]').get('value');this.load(BLT.Env.Urls.ajax,'do=login&_module=checkout&_type=pages&_origin='+BLT.Env.Urls.base+'&email='+email+'&pass='+pass);}else if(tar.hasClass('logout')){try{_g.action('inline-logout',{});}catch(e){}
e.halt();window.location=BLT.Env.Urls.logout+'?return='+BLT.Env.Urls.self;}
else if(tar.hasClass('close-purchase')){try{_g.action('buy-closed',{});}catch(e){}
e.halt();this.closePurchase();}
else if(tar.hasClass('checkout-do-login')){try{_g.action('checkout-login',{});}catch(e){}
e.halt();this.toggleLogin(e,tar);}
else if((tar=BLT.Obj.getParent(tar,'use-billing-address'))){this.toggleShipping();}},toggleShipping:function(){var tar=$('label.use-billing-address');if(!tar){return;}
var v={'firstname':"",'lastname':"",'street':"",'city':"",'state':"",'zip':""};var box=tar.one('input');if(box.get('checked')==false){}
else if(this.store.card!=0){var card=this.store.cards[this.store.card];v=card.address;}
else{for(var i in v){v[i]=$('.b'+i).get('value');}}
for(var i in v){$('.s'+i).setAttribute('value',v[i]);}},toggleLogin:function(e,tar){var p=BLT.Obj.panel;var url=BLT.Obj.getXhrUrl('login',{'flow':'no-reg','showfb':'0','.return':BLT.Env.Urls.self});p.load(url,{'openAfter':true});var _f=function(){$('#checkout-flow').set('value','login');Y.Node.getDOMNode($('form.checkout-form')).submit();};p.on('panel:xhrcomplete',function(e){if(typeof e['do']==='undefined'){return;}
p.ignoreDo=true;_f();});},keydown:function(e){var tar=e.target;},keyup:function(e){var tar=e.target;if(tar.hasClass('hasError')){this.validateField(tar);}
if(tar.get('id')=='quantity'){this.updateTotal();}else if(tar.get('name')=='card'){var cardType=this.getCreditCardType(tar.get('value'));if(cardType){Y.one('span.cards').addClass(cardType);}else{Y.one('span.cards').removeClass('visa');Y.one('span.cards').removeClass('american');Y.one('span.cards').removeClass('mastercard');Y.one('span.cards').removeClass('discover');}}else if(tar.get('name')=='zip'){this.geocodeZip(tar.get('value'));}else if(tar.get('name')=='email'){this.checkLogin(tar.get('value'));}},blur:function(e){var tar=e.target;if(tar.hasClass('validate')){this.validateField(tar);}},updateTotal:function(){var quantity=parseInt(Y.one('#quantity').get('value'));var price=parseInt(Y.one('#price').get('innerHTML'));var newTotal=quantity*price*1;if(newTotal>-1){Y.one('#total').set('innerHTML',newTotal);if(Y.one('#dd-credit')){var av=parseInt(Y.one('#dd-credit').getAttribute('data:avail'),10);var used=av;if(av<newTotal){newTotal-=av;if(Y.one('.cards-file')){Y.one('.cards-file').removeClass('nodisplay');}
if(!Y.one('.cards-file')){Y.one('.billing-wrap').removeClass('nodisplay');}}
else{used=newTotal;newTotal=0;Y.one('#use-dd-credit').set('value',1);if(Y.one('.cards-file')){Y.one('.cards-file').addClass('nodisplay')};Y.one('.billing-wrap').addClass('nodisplay');}
Y.one('#dd-credit').set('innerHTML',used);}
Y.all('.final-total-num').set('innerHTML',newTotal);this.form.hideError();}},validateQuantity:function(){var q=Y.one('#quantity');var quantity=parseInt(q.get('value'));var avail=parseInt(q.getAttribute('data:avail'));var max=parseInt(q.getAttribute('data:max'));if(isNaN(max)||max==0){max=50;}
if(quantity<1){this.form.displayError(Q,'You must enter a valid numerical quantity.');return;}
if(quantity>avail){q.set('value',avail);this.updateTotal();this.form.displayError(q,'There are only '+avail+' vouchers left');}
if(quantity>max){q.set('value',max);this.updateTotal();this.form.displayError(q,'You may only purchase '+max+' voucher(s)');}
if(isNaN(quantity)||quantity==""||quantity==0){q.set('value',1);this.updateTotal();}},getCreditCardType:function(ccnumber){var cardTypes=new Array();cardTypes['visa']=/^4\d{3}-?\d{4}-?\d{4}-?\d{4}$/;cardTypes['mastercard']=/^5[1-5]\d{2}-?\d{4}-?\d{4}-?\d{4}$/;cardTypes['discover']=/^6011-?\d{4}-?\d{4}-?\d{4}$/;cardTypes['american']=/^3[4,7]\d{13}$/;ccnumber=ccnumber.split("-").join("");for(key in cardTypes){if(cardTypes[key].test(ccnumber)){return key;}}
return false;},validateField:function(tar){var fieldVal=tar.get('value');var fieldType=tar.get('type');if(tar.hasClass('multiword')){if(fieldVal!=''&&!(fieldVal.split(" ").length>1)){tar.addClass('hasError');this.form.displayError(tar,'Make sure you enter your first and last names.');}else{this.clearError(tar);}}else if(tar.hasClass('date')){if(fieldVal!=''&&!this.checkExpirationDate(fieldVal)){tar.addClass('hasError');this.form.displayError(tar,'Make sure this is a valid future date.');}else{this.clearError(tar);}}else if(tar.hasClass('email')){if(fieldVal!=''&&!(fieldVal.indexOf(".")>0&&fieldVal.indexOf("@")>0)){tar.addClass('hasError');this.form.displayError(tar,'Make sure this is a valid email address.');}else{this.clearError(tar);}}else if(tar.hasClass('numerical')){if(fieldVal!=''&&!this.isNumeric(fieldVal)){tar.addClass('hasError');this.form.displayError(tar,'Make sure this is a numerical security code.');}else{this.clearError(tar);}}else if(tar.hasClass('zip')){if(fieldVal!=''&&(!(fieldVal.length==5||fieldVal.length==10)||!parseInt(fieldVal,10)>0)){tar.addClass('hasError');this.form.displayError(tar,'Make sure this is a valid US zip code.');}else{this.clearError(tar);}}else if(fieldType=='text'&&tar.hasClass('required')&&fieldVal==''){tar.addClass('hasError');this.form.displayError(tar,'This field must be filled out.');}else if(fieldType=='checkbox'&&tar.hasClass('required')&&tar.get('checked')!=true){tar.addClass('hasError');this.form.displayError(tar,'This box must be checked.');}else{this.clearError(tar);}},checkExpirationDate:function(dateStr){var result=false;var dt=new Date();var fullYear=dt.getFullYear().toString();var normalized=dateStr.replace(/[^a-zA-Z0-9]+/g,'-');var parts=normalized.split("-");if(parts.length>1){if(parts[0]>0&&parts[0]<13){if(parts.length>2){if(parts[1]>0&&parts[1]<32){if(parts[2]>=fullYear){result=true;}else if(parts[2].substring(parts[2].length-2)>=fullYear.substring(fullYear.length-2)){result=true;}}}else{if(parts[1]>=fullYear){result=true;}else if(parts[1].substring(parts[1].length-2)>=fullYear.substring(fullYear.length-2)){result=true;}}}}
return result;},geocodeZip:function(zip){if(zip.length==5&&parseInt(zip)>0){this.load("/ajax/",'do=geocode&_type=pages&_module=checkout&_origin='+BLT.Env.Urls.base+'&zip='+zip);}},checkLogin:function(email){if(!this.AsyncQueue){this.AsyncQueue=new Y.AsyncQueue();}else{this.AsyncQueue.stop();}
this.AsyncQueue.add({fn:function(){this.load(BLT.Env.Urls.ajax,'do=checklogin&_type=pages&_module=checkout&_origin='+BLT.Env.Urls.base+'&email='+email);},context:this,timeout:500});this.AsyncQueue.run();},load:function(url,args){args+='&token='+BLT.Env.session.token;var params={'method':'POST','context':this,'data':args,'timeout':10000,'on':{'failure':function(){},'complete':function(id,o,a){var json=false;try{json=$j.parse(o.responseText);}
catch(e){}
if(!json||json.stat!=1){return;}
if(json.errormsg){return alert(json.errormsg);}
if(json.call=='geocode'){var currentCity=Y.one('input[name=city]').get('value');if(this.city==currentCity){Y.one('.citystate').removeClass('nodisplay');Y.one('input[name=city]').set('value',json.city).simulate("keyup");Y.one('input[name=state]').set('value',json.state).simulate("keyup");var anim=new Y.Anim({node:Y.one('.citystate'),duration:.2,to:{height:40}});anim.run();this.city=json.city;}}else if(json.call=='checklogin'){if(json.islogin){Y.one('.password').removeClass('nodisplay');var anim=new Y.Anim({node:Y.one('.password'),duration:.2,to:{height:40}});anim.run();var covershield=Y.one('.covershield');covershield.removeClass('nodisplay');var passwordField=Y.one('.password input');passwordField.focus().simulate('click');var y=passwordField.getY();var x=passwordField.getX();covershield.setX(x-15);covershield.setY(y+40);Y.all('.billing input').each(function(node){node.setAttribute('disabled',true);});}else{var anim=new Y.Anim({node:Y.one('.password'),duration:.2,to:{height:0}});anim.on('end',function(){Y.one('.password').addClass('nodisplay');Y.one('.covershield').addClass('nodisplay');Y.all('.billing input').each(function(node){node.removeAttribute('disabled');});});anim.run();}}else if(json.call=='login'){if(json.stat==1){Y.one('div.row.password').set('innerHTML','<span style="color: #777;">Thanks, you\'re logged in.</span>');Y.one('.covershield').addClass('nodisplay');Y.all('.billing input').each(function(node){node.removeAttribute('disabled');});}else{alert('Incorrect password. Please try again.');}}}}};Y.io(url,params);},clearError:function(tar){var fieldVal=tar.get('value');if(tar.hasClass('required')&&fieldVal==''){tar.addClass('hasError');this.form.displayError(tar,'This field must be filled out.');}else{tar.removeClass('hasError');this.form.hideError();}},isNumeric:function(sText)
{var ValidChars="0123456789";var IsNumber=true;var Char;for(i=0;i<sText.length&&IsNumber==true;i++)
{Char=sText.charAt(i);if(ValidChars.indexOf(Char)==-1)
{IsNumber=false;}}
return IsNumber;}}
Y.augment(BLT.Class.Checkout,Y.EventTarget);});